const gateway='http://127.0.0.1:8765';
const $=id=>document.getElementById(id);
const status=$('status'),stats=$('stats'),answer=$('answer'),gatewayBadge=$('gateway');
const setStatus=(text,ok=false)=>{status.textContent=text;status.className='status '+(ok?'ok':'err')};
async function api(path,body){const r=await fetch(gateway+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||`Gateway HTTP ${r.status}`);return j}
async function activeTab(){const [tab]=await browser.tabs.query({active:true,currentWindow:true});return tab}
function save(){browser.storage.local.set({provider:$('provider').value,mode:$('mode').value,reasoning:$('reasoning').value})}
function load(){browser.storage.local.get({provider:'auto',mode:'balanced',reasoning:'auto'}).then(s=>{$('provider').value=s.provider;$('mode').value=s.mode;$('reasoning').value=s.reasoning})}
function metric(label,value){return `<div class="stat"><b>${value}</b><span>${label}</span></div>`}
$('provider').addEventListener('change',save);$('mode').addEventListener('change',save);$('reasoning').addEventListener('change',save);load();
(async()=>{try{const r=await fetch(gateway+'/health');const j=await r.json();gatewayBadge.textContent=`Gateway · ${j.version}`;gatewayBadge.style.color='#72d39b';setStatus('Ready.',true)}catch(e){gatewayBadge.textContent='Gateway offline';setStatus('Start meechrtk.service first.')}})();
$('run').addEventListener('click',async()=>{const prompt=$('prompt').value.trim();if(!prompt)return setStatus('Enter a prompt first.');answer.hidden=true;stats.innerHTML='';setStatus('Governing context → routing → executing…',true);try{const r=await api('/v1/execute',{request:prompt,provider:$('provider').value,budget:$('mode').value,reasoning:$('reasoning').value,max_output_tokens:4096,local_ok:true});const o=r.optimized||{};answer.textContent=r.response?.text||'(Provider returned no text)';answer.hidden=false;stats.innerHTML=metric('provider',r.provider.toUpperCase())+metric('context reduction',`${Number(o.reduction||0).toFixed(1)}%`)+metric('tokens',`${Number(o.original_tokens||0).toLocaleString()} → ${Number(o.optimized_tokens||0).toLocaleString()}`)+metric('latency',`${r.response?.latency_ms||0} ms`);setStatus(`Complete · ${r.provider.toUpperCase()} · ${r.response?.model||''}`,true)}catch(e){setStatus(e.message)}});
$('page').addEventListener('click',async()=>{try{const tab=await activeTab();if(!tab?.id)return setStatus('No active tab.');const result=await browser.tabs.sendMessage(tab.id,{type:'MEECHRTK_OPTIMIZE',budget:$('mode').value});if(!result?.ok)throw new Error(result?.error||'Optimization failed.');stats.innerHTML=metric('context reduction',`${Number(result.reduction||0).toFixed(1)}%`)+metric('tokens',`${Number(result.originalTokens||0).toLocaleString()} → ${Number(result.optimizedTokens||0).toLocaleString()}`);setStatus('Current AI prompt optimized. Review it, then send normally.',true)}catch(e){setStatus(e.message)}});
$('restore').addEventListener('click',async()=>{try{const tab=await activeTab();const r=await browser.tabs.sendMessage(tab.id,{type:'MEECHRTK_RESTORE'});if(!r?.ok)throw new Error(r?.error||'Nothing to restore.');setStatus('Original prompt restored.',true)}catch(e){setStatus(e.message)}});
$('copy').addEventListener('click',async()=>{if(!answer.textContent)return;await navigator.clipboard.writeText(answer.textContent);setStatus('Response copied.',true)});
